### ISSUE TITLE
Issues with upgrade_mutex

### ISSUE THREAD

**Issue by austin-beer** [HowardHinnant/upgrade_mutex#2]
1. a. I believe that [upgrade_mutex::try_unlock_shared_and_lock_until()](https://github.com/HowardHinnant/upgrade_mutex/blob/e658a06e7b1a62f8b16cb48fc22f28d82bb415e7/upgrade_mutex.h#L399) should wait on `gate1_` until there is no writer and no upgrader and then it should decrement the reader count and set the `write_entered_` flag and then it should wait on `gate2_` until there are no more readers. This prevents new readers from taking a shared or upgrade lock while this function is waiting to take the exclusive lock.
b. Also, right now since it is only waiting on `gate2_` it won't get signaled after any of the `unlock*()` functions are called.
1. I believe that [upgrade_mutex::try_unlock_shared_and_lock_upgrade_until()](https://github.com/HowardHinnant/upgrade_mutex/blob/e658a06e7b1a62f8b16cb48fc22f28d82bb415e7/upgrade_mutex.h#L420) should wait on `gate1_` instead of `gate2_`. Right now since it is only waiting on `gate2_` it won't get signaled after `unlock_upgrade()` is called.
1. a. I believe that [upgrade_mutex::try_unlock_upgrade_and_lock_until()](https://github.com/HowardHinnant/upgrade_mutex/blob/e658a06e7b1a62f8b16cb48fc22f28d82bb415e7/upgrade_mutex.h#L441) should decrement the reader count and set the `write_entered_` flag and then it should wait on `gate2_` until there are no more readers. This prevents new readers from taking a shared lock while this function is waiting to take the exclusive lock.
b. Also, right now `gate2_` only gets signaled when the reader count is zero but this function currently waits for the reader count to reach 1.

I've already fixed these issues in the copy of upgrade_mutex that exists in Boost.Thread: https://github.com/boostorg/thread/blob/develop/include/boost/thread/v2/shared_mutex.hpp.

Are these issues all valid or have I missed something? Thank you for taking a look at this.

**Comment by HowardHinnant** [comment]
So far I've just considered 1.

It seems to me that this would just make it easier for the casual programmer to virtually deadlock his entire process.  If two threads execute `try_unlock_shared_and_lock_until` at the same time with very long time outs, the current code blocks only those two threads.  Your change blocks every thread attempting to get any type of access.

I firmly recommend against any variation of a `try_` function which would hinder any variation of a `lock_` function.  I consider the act of doing so a bug.

**Comment by austin-beer** [comment]
Okay, thanks for explaining the design decisions you made. I've split my points into (a) and (b) parts because I believe the (b) parts still need to be addressed regardless. How would you address 1.b.?

> I firmly recommend against any variation of a `try_` function which would hinder any variation of a `lock_` function. I consider the act of doing so a bug.

In your existing implementation, calling `try_lock_until()` takes the `write_entered_` flag and then waits for all readers to unlock. This blocks any further calls to `lock_shared()`, which violates your statement. Is this then a bug in your existing implementation? This existing behavior is where I got the idea that there might be issues with `try_unlock_shared_and_lock_until() ` and `try_unlock_upgrade_and_lock_until()` since they don't behave the same as `try_lock_until()`.

**Comment by austin-beer** [comment]
There's one other unrelated minor issue I've found. Let's say the maximum number of readers has been reached, and one of the readers is an upgrade reader. Then one thread calls `lock()` and another thread calls `lock_shared()`. Both will wait on `gate1_`. Then a third thread calls `unlock_shared()`. Since the number of readers is now one less than the maximum, `gate1_.notify_one()` will be called, which _should_ wake up the `lock_shared()` call. But it might wake up the `lock()` call instead, which can't progress since there is still an upgrade reader. `lock_shared()` could have progressed but didn't because it wasn't woken up. To fix this I think `gate1_.notify_one()` needs to be changed to `gate1_.notify_all()`.

**Comment by HowardHinnant** [comment]
Thanks, not forgotten, just busy.

**Comment by austin-beer** [comment]
I'm closing this issue as OBE. My latest recommendations for fixes and improvements to this implementation are documented in pull request #3.
